In [10]:
import numpy as np

#Create a rank 1 array
a = np.array([0,1,2])
print(type(a))
print(a[0])


<class 'numpy.ndarray'>
0


In [11]:
#Create a 3x3 array
a = np.zeros((3,3))
print(a)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [16]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
a = np.array([9,10])
b = np.array([11,12])
print(a.dot(b))
print(np.dot(a,b))
print(np.dot(x,y))
print(np.sum(x))

219
219
[[19 22]
 [43 50]]
10


In [18]:
b = a+x
print(b)

[[10 12]
 [12 14]]
